import type React from 'react'

export type IconProps = React.SVGAttributes<SVGElement>

export { BilibiliIcon } from './icons/BilibiliIcon'
export { BriefcaseIcon } from './icons/BriefcaseIcon'
export { CursorClickIcon } from './icons/CursorClickIcon'
export { ExternalLinkIcon } from './icons/ExternalLinkIcon'
export { GitHubIcon } from './icons/GitHubIcon'
export { LightningIcon } from './icons/LightningIcon'
export { MailIcon } from './icons/MailIcon'
export { MoonIcon } from './icons/MoonIcon'
export { SparkleIcon } from './icons/SparkleIcon'
export { SunIcon } from './icons/SunIcon'
export { TelegramIcon } from './icons/TelegramIcon'
export { TiltedSendIcon } from './icons/TiltedSendIcon'
export { TwitterIcon } from './icons/TwitterIcon'
export { UserSecurityIcon } from './icons/UserSecurityIcon'
export { UsersIcon } from './icons/UsersIcon'
export { YouTubeIcon } from './icons/YouTubeIcon'
