import type React from 'react'

export type IconProps = React.SVGAttributes<SVGElement>

export { BilibiliIcon } from './icons/BilibiliIcon'
export { BriefcaseIcon } from './icons/BriefcaseIcon'
export { CalendarIcon } from './icons/CalendarIcon'
export { CheckDoubleTickIcon } from './icons/CheckDoubleTickIcon'
export { CloudIcon } from './icons/CloudIcon'
export { CursorClickIcon } from './icons/CursorClickIcon'
export { CursorIcon } from './icons/CursorIcon'
export { ExternalLinkIcon } from './icons/ExternalLinkIcon'
export { GitHubIcon } from './icons/GitHubIcon'
export { HourglassIcon } from './icons/HourglassIcon'
export { LightningIcon } from './icons/LightningIcon'
export { MailIcon } from './icons/MailIcon'
export { MinusCircleIcon } from './icons/MinusCircleIcon'
export { MoonIcon } from './icons/MoonIcon'
export { PencilSwooshIcon } from './icons/PencilSwooshIcon'
export { ScriptIcon } from './icons/ScriptIcon'
export { SparkleIcon } from './icons/SparkleIcon'
export { SunIcon } from './icons/SunIcon'
export { TagIcon } from './icons/TagIcon'
export { TelegramIcon } from './icons/TelegramIcon'
export { TiltedSendIcon } from './icons/TiltedSendIcon'
export { TwitterIcon } from './icons/TwitterIcon'
export { UFOIcon } from './icons/UFOIcon'
export { UserSecurityIcon } from './icons/UserSecurityIcon'
export { UsersIcon } from './icons/UsersIcon'
export { YouTubeIcon } from './icons/YouTubeIcon'
